server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.h2.Driver
    name: sa
    password: sa
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mounesh.acharya51@gmail.com
    password: hlzlavzartpkvyvz
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true